name: DevOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Calculate version
        id: semver-app
        uses: PaulHatch/semantic-version@v6.0.2
        with:
          tag_prefix: ""
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat:"
          version_format: "${major}.${minor}.${patch}"

      - name: Set lowercase image name
        run: echo "IMAGE_NAME=ghcr.io/$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:staging \
            -t $IMAGE_NAME:${{ steps.semver-app.outputs.version }} \
            -f DevOpsWebApplication/Dockerfile \
            .
          docker push $IMAGE_NAME --all-tags

      - name: Create release notes
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.semver-app.outputs.version }}
          generateReleaseNotes: true
          skipIfReleaseExists: true
          body: |
            This release includes the following container image:
            ${{ env.IMAGE_NAME }}:${{ steps.semver-app.outputs.version }}

      - name: Deliver Docker Compose file to staging
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          source: "docker-compose.yaml"
          target: dowa/

      - name: Run Docker Compose on staging server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ vars.STAGING_SERVER_IP }}
          username: ${{ vars.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd dowa
            docker compose pull
            docker compose up -d